In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('E:\\Магистратура\\3\\Машинное обучение\\healthcare-dataset-stroke-data.csv', sep=',')
print(df.head(5), "\n")
print(df.info(), "\n")

      id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1   

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110

In [4]:
# отбор числовых колонок (Числовые признаки)

df_numeric = df.select_dtypes(include=[np.number])
numeric_cols = df_numeric.columns.values
print(numeric_cols)
print(df_numeric)

['id' 'age' 'hypertension' 'heart_disease' 'avg_glucose_level' 'bmi'
 'stroke']
         id   age  hypertension  heart_disease  avg_glucose_level   bmi  \
0      9046  67.0             0              1             228.69  36.6   
1     51676  61.0             0              0             202.21   NaN   
2     31112  80.0             0              1             105.92  32.5   
3     60182  49.0             0              0             171.23  34.4   
4      1665  79.0             1              0             174.12  24.0   
...     ...   ...           ...            ...                ...   ...   
5105  18234  80.0             1              0              83.75   NaN   
5106  44873  81.0             0              0             125.20  40.0   
5107  19723  35.0             0              0              82.99  30.6   
5108  37544  51.0             0              0             166.29  25.6   
5109  44679  44.0             0              0              85.28  26.2   

      stroke  
0   

In [6]:
# отбор нечисловых колонок (Категориальные признаки)

df_non_numeric = df.select_dtypes(exclude=[np.number])
non_numeric_cols = df_non_numeric.columns.values
print(non_numeric_cols)
print(df_non_numeric)

['gender' 'ever_married' 'work_type' 'Residence_type' 'smoking_status']
      gender ever_married      work_type Residence_type   smoking_status
0       Male          Yes        Private          Urban  formerly smoked
1     Female          Yes  Self-employed          Rural     never smoked
2       Male          Yes        Private          Rural     never smoked
3     Female          Yes        Private          Urban           smokes
4     Female          Yes  Self-employed          Rural     never smoked
...      ...          ...            ...            ...              ...
5105  Female          Yes        Private          Urban     never smoked
5106  Female          Yes  Self-employed          Urban     never smoked
5107  Female          Yes  Self-employed          Rural     never smoked
5108    Male          Yes        Private          Rural  formerly smoked
5109  Female          Yes       Govt_job          Urban          Unknown

[5110 rows x 5 columns]


In [7]:
df["work_type"].value_counts().sort_index()

work_type
Govt_job          657
Never_worked       22
Private          2925
Self-employed     819
children          687
Name: count, dtype: int64

In [8]:
# Кодирование качественных признаков

# OrdinalEncoder

from sklearn.compose import make_column_selector as selector

categorical_columns_selector = selector(dtype_include=object)
categorical_columns = categorical_columns_selector(df)
categorical_columns

['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']

In [9]:
df_cat = df[categorical_columns] #отберем только те столбцы в которых присутствует категориальная перемнная
df_cat.head()

gender ever_married      work_type Residence_type   smoking_status
0    Male          Yes        Private          Urban  formerly smoked
1  Female          Yes  Self-employed          Rural     never smoked
2    Male          Yes        Private          Rural     never smoked
3  Female          Yes        Private          Urban           smokes
4  Female          Yes  Self-employed          Rural     never smoked

In [12]:
from sklearn.preprocessing import OrdinalEncoder

education_column = df_cat[["work_type"]]
print(df_cat['work_type'].unique()) #посмотрим какие виды образования присутствуют в выборке
encoder = OrdinalEncoder() # вызываем кодировщик
encoder = encoder.fit(df_cat[['work_type']])
df_cat['work_type'] = encoder.transform(df_cat[['work_type']])
df_cat

[2. 3. 0. 4. 1.]


C:\Users\anton\AppData\Local\Temp\ipykernel_12376\18335339.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cat['work_type'] = encoder.transform(df_cat[['work_type']])


gender ever_married  work_type Residence_type   smoking_status
0       Male          Yes        2.0          Urban  formerly smoked
1     Female          Yes        3.0          Rural     never smoked
2       Male          Yes        2.0          Rural     never smoked
3     Female          Yes        2.0          Urban           smokes
4     Female          Yes        3.0          Rural     never smoked
...      ...          ...        ...            ...              ...
5105  Female          Yes        2.0          Urban     never smoked
5106  Female          Yes        3.0          Urban     never smoked
5107  Female          Yes        3.0          Rural     never smoked
5108    Male          Yes        2.0          Rural  formerly smoked
5109  Female          Yes        0.0          Urban          Unknown

[5110 rows x 5 columns]

In [13]:
print(encoder.categories_)
print(len(encoder.categories_[0]))
print(df_cat['work_type'].unique())
df_cat['work_type'].unique().size

[array([0., 1., 2., 3., 4.])]
5
[2. 3. 0. 4. 1.]


5

In [14]:
# OneHotEncoder

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
encoder = encoder.fit(df_cat[['work_type']])
education_encoded = encoder.transform(df_cat[['work_type']])
education_encoded

C:\Users\anton\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [15]:
feature_names = encoder.get_feature_names_out(input_features=["work_type"]) 
# получаем виды образования и на их основе создаем столбцы
education_encoded = pd.DataFrame(education_encoded, columns=feature_names)
education_encoded

work_type_0.0  work_type_1.0  work_type_2.0  work_type_3.0  \
0               0.0            0.0            1.0            0.0   
1               0.0            0.0            0.0            1.0   
2               0.0            0.0            1.0            0.0   
3               0.0            0.0            1.0            0.0   
4               0.0            0.0            0.0            1.0   
...             ...            ...            ...            ...   
5105            0.0            0.0            1.0            0.0   
5106            0.0            0.0            0.0            1.0   
5107            0.0            0.0            0.0            1.0   
5108            0.0            0.0            1.0            0.0   
5109            1.0            0.0            0.0            0.0   

      work_type_4.0  
0               0.0  
1               0.0  
2               0.0  
3               0.0  
4               0.0  
...             ...  
5105            0.0  
5106            0.0  
5107            0.0  
5108            0.0  
5109            0.0  

[5110 rows x 5 columns]

In [16]:
df_cat_new=df_cat.join(education_encoded)
df_cat_new=df_cat_new.drop(df_cat_new[['work_type']],axis=1)
df_cat_new

gender ever_married Residence_type   smoking_status  work_type_0.0  \
0       Male          Yes          Urban  formerly smoked            0.0   
1     Female          Yes          Rural     never smoked            0.0   
2       Male          Yes          Rural     never smoked            0.0   
3     Female          Yes          Urban           smokes            0.0   
4     Female          Yes          Rural     never smoked            0.0   
...      ...          ...            ...              ...            ...   
5105  Female          Yes          Urban     never smoked            0.0   
5106  Female          Yes          Urban     never smoked            0.0   
5107  Female          Yes          Rural     never smoked            0.0   
5108    Male          Yes          Rural  formerly smoked            0.0   
5109  Female          Yes          Urban          Unknown            1.0   

      work_type_1.0  work_type_2.0  work_type_3.0  work_type_4.0  
0               0.0            1.0            0.0            0.0  
1               0.0            0.0            1.0            0.0  
2               0.0            1.0            0.0            0.0  
3               0.0            1.0            0.0            0.0  
4               0.0            0.0            1.0            0.0  
...             ...            ...            ...            ...  
5105            0.0            1.0            0.0            0.0  
5106            0.0            0.0            1.0            0.0  
5107            0.0            0.0            1.0            0.0  
5108            0.0            1.0            0.0            0.0  
5109            0.0            0.0            0.0            0.0  

[5110 rows x 9 columns]

In [17]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder() # вызываем кодировщик
encoder = encoder.fit(df_cat[['work_type']])
df_cat['work_type'] = encoder.transform(df_cat[['work_type']])
df_cat

C:\Users\anton\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\anton\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
C:\Users\anton\AppData\Local\Temp\ipykernel_12376\2357235040.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cat['work_type'] = encoder.transform(df_cat[['work_type']])


gender ever_married  work_type Residence_type   smoking_status
0       Male          Yes          2          Urban  formerly smoked
1     Female          Yes          3          Rural     never smoked
2       Male          Yes          2          Rural     never smoked
3     Female          Yes          2          Urban           smokes
4     Female          Yes          3          Rural     never smoked
...      ...          ...        ...            ...              ...
5105  Female          Yes          2          Urban     never smoked
5106  Female          Yes          3          Urban     never smoked
5107  Female          Yes          3          Rural     never smoked
5108    Male          Yes          2          Rural  formerly smoked
5109  Female          Yes          0          Urban          Unknown

[5110 rows x 5 columns]

In [18]:
print(encoder.classes_)
print(len(encoder.classes_))
print(df_cat['work_type'].unique())
df_cat['work_type'].unique().size

[0. 1. 2. 3. 4.]
5
[2 3 0 4 1]


5

In [20]:
# Масштабирование признаков

from sklearn.preprocessing import StandardScaler

X_train = np.array([[ 1., -1., 2.],
                     [ 2., 0., 0.],
                     [ 0., 1., -1.]])

scaler = StandardScaler()
scaler.fit(X_train)
print('Математическое ожидание')
print(scaler.mean_)
print('Дисперсия')
print(scaler.var_)
print('Преобразованный набор')
print(scaler.transform(X_train))

Математическое ожидание
[1.         0.         0.33333333]
Дисперсия
[0.66666667 0.66666667 1.55555556]
Преобразованный набор
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [21]:
from sklearn.preprocessing import MinMaxScaler

X_train = np.array([[ 1., -1., 2.],
                     [ 2., 0., 0.],
                    [ 0., 1., -1.]])

min_max_scaler = MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_train_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [22]:
# MaxAbsScaler

from sklearn.preprocessing import MaxAbsScaler

X_train = np.array([[ 1., -1., 2.],
                     [ 2., 0., 0.],
                     [ 0., 1., -1.]])

max_abs_scaler = MaxAbsScaler()
X_train_maxabs = max_abs_scaler.fit_transform(X_train)
X_train_maxabs

array([[ 0.5, -1. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.5]])

In [23]:
# Нормализация

from sklearn import preprocessing

X = [[ 1., -1., 2.],
    [ 2., 0., 0.],
    [ 0., 1., -1.]]

X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])